module.exports = {
    WRONG_GOOGLE_CLIENT_ID       : 'WRONG_GOOGLE_CLIENT_ID',
    WRONG_GOOGLE_CLIENT_SECRET   : 'WRONG_GOOGLE_CLIENT_SECRET',
    WRONG_GOOGLE_REDIRECT_URI    : 'WRONG_GOOGLE_REDIRECT_URI',
    ACCESS_BACKEND_REQUEST_ERROR : 'ACCESS_BACKEND_REQUEST_ERROR'
};
