module.exports = {
    FORMAT_ERROR                 : 'FORMAT_ERROR',
    INVALID_CREDENTIALS          : 'INVALID_CREDENTIALS',
    ACCESS_IS_TEMPORARILY_DENIED : 'ACCESS_IS_TEMPORARILY_DENIED',
    OPEN_CLOSE_DOOR_ERROR        : 'OPEN_CLOSE_DOOR_ERROR'
};
